init commit

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -13,16 +13,16 @@ permissions:
 jobs:
   build:
     name: Build DB
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     steps:
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: 1.18
-        id: go
-
       - name: Check out code into the Go module directory
-        uses: actions/checkout@v4
+        uses: actions/checkout@v2
+
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version-file: go.mod
+        id: go
 
       - name: Build the binary
         run: make build
@@ -39,6 +39,12 @@ jobs:
       - name: Move DB
         run: mv cache/db/javadb.tar.gz .
 
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_TOKEN }}
+
       - name: Login to GitHub Packages Container registry
         uses: docker/login-action@v3
         with:
@@ -46,9 +52,44 @@ jobs:
           username: ${{ env.GH_USER }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Upload assets to GHCR
+      - name: Install oras
         run: |
-          oras version
-          oras push --artifact-type application/vnd.khulnasoft.tunnel.config.v1+json \
-          ghcr.io/${{ github.repository }}:${DB_VERSION} \
-          javadb.tar.gz:application/vnd.khulnasoft.tunnel.javadb.layer.v1.tar+gzip
+          curl -LO https://github.com/oras-project/oras/releases/download/v1.2.0/oras_1.2.0_linux_amd64.tar.gz
+          tar -xvf ./oras_1.2.0_linux_amd64.tar.gz          
+
+      - name: Upload assets to registries
+        run: |
+          lowercase_repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
+          ./oras version
+          
+          echo "Starting artifact upload process..."
+          
+          # Define an array of registry base URLs and their corresponding repository names
+          declare -A registries=(
+            ["ghcr.io"]="${lowercase_repo}"
+            ["docker.io"]="${lowercase_repo}"
+          )
+          
+          # Special case for docker.io if the organization is 'khulnasoft'
+          if [[ "${lowercase_repo}" == "khulnasoft/"* ]]; then
+            registries["docker.io"]="khulnasoft/${lowercase_repo#khulnasoft/}"
+            echo "Docker Hub repository adjusted for khulnasoft: ${registries["docker.io"]}"
+          fi
+          
+          # Loop through each registry and push the artifact
+          for registry in "${!registries[@]}"; do
+            repo_name=${registries[$registry]}
+            full_registry_url="${registry}/${repo_name}"
+            echo "Processing registry: ${full_registry_url}"
+        
+            if ./oras push --artifact-type application/vnd.khulnasoft.tunnel.config.v1+json \
+              "${full_registry_url}:${DB_VERSION}" \
+              javadb.tar.gz:application/vnd.khulnasoft.tunnel.javadb.layer.v1.tar+gzip; then
+              echo "Successfully pushed to ${full_registry_url}:${DB_VERSION}"
+            else
+              echo "Failed to push to ${full_registry_url}:${DB_VERSION}"
+              exit 1
+            fi
+          done
+          
+          echo "Artifact upload process completed."
